-- Intentionally left as a no-op.
--
-- The original migration granted SELECT on every participants row to every
-- authenticated Supabase user. The application does not need that access:
-- participant and administrator operations use authenticated Edge Functions
-- with the service role.
--
-- Keep this migration version so migration ordering remains stable.